name: mento_grupo2
channels:
  - plotly
  - conda-forge
  - anaconda
  - defaults
dependencies:

  - jupyter_client=7.1.2
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.1.5
  - pip=21.2.2
  - plotly=5.6.0
  - python=3.6.13
  - python-dateutil=2.8.2
  - python_abi=3.6
  - scipy=1.5.2
  - seaborn=0.11.2
  - sqlite=3.38.3
  - statsmodels=0.12.2
  
  